### ISSUE TITLE
Add monitoring of vets-api -> MAS claim handoff to Datadog

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1077] opened 2023-02-10 22:57 UTC
**User Story**

As a VRO engineer/product owner, I want an easy way to monitor the integration that notifies MAS of all va.gov-submitted 526 claims, so that I can review traffic and be alerted to major issues.

**Acceptance Criteria**

1. Set up monitoring in vets-api Datadog to track claims being passed from vets-api to MAS (ie. the claims currently tracked in #rrd-to-mas-all-claims in Slack). 
2. Set up an alert to notify when no claims have been passed to the MAS endpoint in X timeframe (please recommend an appropriate timeframe and/or bring it to product owners/managers for discussion)
3. Set up an alert to notify when no claims have received a 200 success response from the MAS endpoint in X timeframe (please recommend an appropriate timeframe and/or bring it to product owners/managers for discussion)

**Notes about work**
- We have not previously interacted with the vets-api/va.gov instance of Datadog. See [slack thread](https://dsva.slack.com/archives/C031RRFCHV1/p1676061715668929); we can reach out to Jesse House and/or Taylor Reyes Sihapanya about it

**Comment by amylai-nava** [comment] 2023-03-14 22:29
@nanotone is this done done, meaning @dianagriffin no longer needs to be monitor `#rrd-to-mas-all-claims`?

**Comment by nanotone** [comment] 2023-03-15 19:12
@amylai-nava @dianagriffin The last quarter-mile of this is blocked until Datadog write access is rolled out to VFS teams in the near future -- on the order of a few weeks. I've described our desired setup in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081#issuecomment-1470625961) on the Platform team's ticket.

In the meantime, I'm happy to keep monitoring our Slack channels (I know there is always more unpacking to be done, it never ends).

**Comment by amylai-nava** [comment] 2023-03-15 20:46
Closing this ticket as done, because Yang has:
- Added two new StatsD metrics in vets-api to track successes and failures of one particular external API call: https://github.com/department-of-veterans-affairs/vets-api/pull/12021
- Confirmed that the new metrics are visible in the Datadog Metrics Explorer

Will create a new ticket (to be linked) to track the remaining steps needed once Datadog write access is granted.

**Closed by amylai-nava** 2023-03-15 20:46 UTC
Labels: Engineer
